### ISSUE TITLE
Starting auth

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/external-spotify#1]
### Desc

Attaching the spotify authorization, which would need 1-2 basic pages.
As a first step, I need to get the tokens after login.

### Subtasks

- [x] integrate spotify wrapper
- [x] setting up auth on back-end
- [x] index should redirect to login 
- [x] callback page
- [x] get code, if not present
- [x] get tokens, if not present
