### ISSUE TITLE
Batch actions

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/external-spotify#10]
### Desc

Given, that the basic actions are available for songs, I want to extend its use case by reducing the number of clicks

### Subtasks

- [x] edit row -> clicked rows will be part of the selected rows, which can be modified together.
- [x] batch version of existing apis on back-end
- [x] the three table should get a grouping icon (like all songs in exact matches for example)
