### ISSUE TITLE
visual feedback

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/external-spotify#12]
### Desc

I need some feedback after making actions. The parsing and searching is fine, since they are pushed to the arrays, but the action buttons (like song, save album, follow artist) are unresponsive.

### Subtasks

- [x] spinner component
- [x] variable, which is set true before request and after in the subscribe method
- [x] spinner integration with the variable
- [x] small css changes (done actions are paired with colors
