### ISSUE TITLE
Integrate track status to model

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/external-spotify#14]
### Desc

The colorized icons are a good way to show that an action was successful, however it is misleading in its current form.

I'd need to integrate like/save/follow into the model, so the song would be correctly attached to the given user.

### Subtasks

- [x] extend model with likedTrack, savedAlbum, followedArtist
- [x] back-end requests to get these infos for the user by id (they need to go in batch to reduce the number of queries to a minimum)
- [x] map these queries into the get track endpoint -> currently I cannot map them in batch, so the front-end will send another request
- [x] change the manual like/save/follow to a loop property check

**Comment by hajdumozes** [comment]
Check Current User's Saved Tracks endpoint seems suitable
