### ISSUE TITLE
Add songs to playlist

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/external-spotify#19]
### Desc

Although parsing could be a problem, it would still be possible to add tracks to playlists, or create a new one.

### Subtasks

- [x] get playlists
- [x] add to playlist (remove existent?)
- [x] save to local storage
- [ ] create new playlist
