### ISSUE TITLE
Starting pages

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/external-spotify#2]
### Desc

I've no need for the default angular index page, so it should go.
Actually, for a start one page is enough, so it's okay as an empty page.
Later probably a header would get there.

The callback page is enough as a notifier, that the login was successful, and a loading spinner could be added, if the redirect takes too much time.

There's also a need for the main (for now) page, which would be local-tags, and the callback page would redirect here after finishing the auth process.

### Subtasks

- [x] remove the index page content
- [x] create local-tags page
- [x] redirect to local-tags page from callback after successful auth
