### ISSUE TITLE
Id3 tag parse

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/external-spotify#4]
### Desc

Using the file upload field I need to get the id3 tags of the selected files, which will be uploaded and handled by the back-end later.

### Subtasks

- [x] html file upload field addition
- [x] music-metadata-browser node module addition
- [x] change listener usesthe music-metadata-browser node module to get the id3 tag
- [x] some temporary html to show that the parse was successful
