### ISSUE TITLE
refresh tokens

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/external-spotify#6]
### Desc

Currently, after login the back-end sets the tokens, and the user has 60 minutes. Right now there are no request toward spotify, but with them a token refresh will be mandatory

### Subtasks

- [x] implement refresh token in auth service
- [x] all requests should be accompanied with a token
- [x] all response should be accompanied with a token
- [x] all queries should trigger a token refresh
