### ISSUE TITLE
Dissolve singleton spotifyApi

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/external-spotify#7]
### Desc

In the current form the spotify api could only serve one client. It could be altered by setters, but it wouldn't be a solution. It's a lot simpler to just send tokens all the way, and create spotifyApis for every request, and serve those on separate threads.

### Subtasks

- [x] alter current methods to get a token, which they will use to build a spotifyApi
- [x] auth service will always get the params they need at the moment
- [x] for every request there must be a credentials plus param
