### ISSUE TITLE
Track actions

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/external-spotify#8]
### Desc

Having the tracks and all the ids related to them, the user can make actions to them. These should be in a separate actions column for the related tables

### Subtasks

- [x] actions column
- [x] love icon and action for like song (spotify - save tracks for user?)
- [x] follow album (spotify - follow album or artist)
- [x] follow artist (spotify - follow album or artist)
- [ ] remove from list (should remove from the component list)

### Optional

- [ ] batch actions for all the above regarded to exact and multiple results
- [ ] reverse (unlike, unfollow)
- [ ] visual feedback
